### ISSUE TITLE
Create Step-by-Step Demo Showing How to use the `gogs` package

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs-demo#1]
We have got a _working_ implementation of the `gogs` interface: https://github.com/dwyl/gogs 📦 🚀 🎉 
(_works on `localhost` and **`Mock`** tests all pass on `CI`: [gogs/actions/workflows/ci](https://github.com/dwyl/gogs/actions/workflows/ci.yml) ... but it's still tedious to setup ..._) ⌛ 🙄 

We need a step-by-step example/demo **`Phoenix`** App that shows _exactly_ how to get it all working!

# Todo

+ [ ] Create a tutorial Rich Text Editor that saves data to https://gogs-server.fly.dev/ via `gogs`
+ [ ] Document all the steps to set up including the SSH key for `Gogs.push`
+ [ ] No need for a Database or Authentication; leave it totally open but only allow editing the `README.md`
> We can get fancy _later_! This one is very deliberatly simple!
+ [ ] Borrow from previous work: 
  + [ ] `README.md` structure/steps: https://github.com/dwyl/elixir-auth-google-demo 
  + [ ] Rich Text Editor in Phoenix: https://github.com/nelsonic/amemo
+ [ ] Create new Fly.io Org
+ [ ] Deploy it!!

**Comment by nelsonic** [comment]
Going to try and get this done _now_ as we need it! 🧑‍💻

**Comment by nelsonic** [comment]
"Paint" logo: 
![gogs-demo-logo](https://user-images.githubusercontent.com/194400/167251193-e0cb2874-88f0-4a78-a752-1a0f9d253e10.png)

😉

**Comment by nelsonic** [comment]
Rendered markdown:
![image](https://user-images.githubusercontent.com/194400/168069048-15dd5b50-235c-4cbe-9f3e-fb306933e17c.png)

**Comment by nelsonic** [comment]
No point extending the `gogs-demo` ... transferring this to `gitea-demo` ...
